/*
================================================================================
elevator6x2.asm:  6-floor, 2-car collective elevator controller for the TTLC

Generated by gen_elevator6x2.py - edit that, not this.  I/O map: elevator6x2.h.

Every scan: latch the buttons into the sticky request indicators, detect a
rising edge of the TICK input, then run both cars.  On a tick a car either
keeps its door open (two ticks), closes it, opens it because a request is
at its floor (clearing that floor's indicators), or moves one floor toward
the nearest pending request, continuing in its direction while there is
something ahead (collective control).  Both cars answer hall calls; car 1
has priority at a floor where both stand.

asmsyntax=mc14500b
================================================================================
*/

include <elevator6x2.h>

loop:
    nopo                   // scan: outputs out, inputs in

    // ----------------------------------------------------------------------
    // sticky request indicators: output n |= input n  (hall calls, both cabins)
    // ----------------------------------------------------------------------
    ld     IN+0
    or     0
    sto    0
    ld     IN+1
    or     1
    sto    1
    ld     IN+2
    or     2
    sto    2
    ld     IN+3
    or     3
    sto    3
    ld     IN+4
    or     4
    sto    4
    ld     IN+5
    or     5
    sto    5
    ld     IN+6
    or     6
    sto    6
    ld     IN+7
    or     7
    sto    7
    ld     IN+8
    or     8
    sto    8
    ld     IN+9
    or     9
    sto    9
    ld     IN+10
    or     10
    sto    10
    ld     IN+11
    or     11
    sto    11
    ld     IN+12
    or     12
    sto    12
    ld     IN+13
    or     13
    sto    13
    ld     IN+14
    or     14
    sto    14
    ld     IN+15
    or     15
    sto    15
    ld     IN+16
    or     16
    sto    16
    ld     IN+17
    or     17
    sto    17
    ld     IN+18
    or     18
    sto    18
    ld     IN+19
    or     19
    sto    19
    ld     IN+20
    or     20
    sto    20
    ld     IN+21
    or     21
    sto    21

    // ----------------------------------------------------------------------
    // tick edge: TICK_EDGE = TICK & !TICK_LAST
    // ----------------------------------------------------------------------
    ld     TICK
    andc   TICK_LAST
    sto    TICK_EDGE
    ld     TICK
    sto    TICK_LAST

    // ----------------------------------------------------------------------
    // car 1: start at floor 0 when no position bit is set yet (after reset)
    // ----------------------------------------------------------------------
    ld     POS1+0
    or     POS1+1
    or     POS1+2
    or     POS1+3
    or     POS1+4
    or     POS1+5
    ldc    RR              // RR = position unknown
    or     POS1+0
    sto    POS1+0

    // ----------------------------------------------------------------------
    // car 1: requests that concern this car, per floor
    // ----------------------------------------------------------------------
    // R_f = cabin button f | hall calls at f
    ld     HALL_UP0
    or     CAB1+0
    sto    R0
    ld     HALL_UP1
    or     HALL_DN1
    or     CAB1+1
    sto    R1
    ld     HALL_UP2
    or     HALL_DN2
    or     CAB1+2
    sto    R2
    ld     HALL_UP3
    or     HALL_DN3
    or     CAB1+3
    sto    R3
    ld     HALL_UP4
    or     HALL_DN4
    or     CAB1+4
    sto    R4
    ld     HALL_DN5
    or     CAB1+5
    sto    R5

    // ----------------------------------------------------------------------
    // car 1: is there a request above / below the current floor?
    // ----------------------------------------------------------------------
    ld     R5
    and    POS1+4
    sto    ANY_ABOVE
    ld     R4
    or     R5
    and    POS1+3
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R3
    or     R4
    or     R5
    and    POS1+2
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R2
    or     R3
    or     R4
    or     R5
    and    POS1+1
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R1
    or     R2
    or     R3
    or     R4
    or     R5
    and    POS1+0
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R0
    and    POS1+1
    sto    ANY_BELOW
    ld     R0
    or     R1
    and    POS1+2
    or     ANY_BELOW
    sto    ANY_BELOW
    ld     R0
    or     R1
    or     R2
    and    POS1+3
    or     ANY_BELOW
    sto    ANY_BELOW
    ld     R0
    or     R1
    or     R2
    or     R3
    and    POS1+4
    or     ANY_BELOW
    sto    ANY_BELOW
    ld     R0
    or     R1
    or     R2
    or     R3
    or     R4
    and    POS1+5
    or     ANY_BELOW
    sto    ANY_BELOW

    // ----------------------------------------------------------------------
    // car 1: is there a request at the current floor?
    // ----------------------------------------------------------------------
    ld     R0
    and    POS1+0
    sto    REQ_HERE
    ld     R1
    and    POS1+1
    or     REQ_HERE
    sto    REQ_HERE
    ld     R2
    and    POS1+2
    or     REQ_HERE
    sto    REQ_HERE
    ld     R3
    and    POS1+3
    or     REQ_HERE
    sto    REQ_HERE
    ld     R4
    and    POS1+4
    or     REQ_HERE
    sto    REQ_HERE
    ld     R5
    and    POS1+5
    or     REQ_HERE
    sto    REQ_HERE

    // ----------------------------------------------------------------------
    // car 1: what this tick does (everything is gated by TICK_EDGE)
    // ----------------------------------------------------------------------
    // STAY    = tick & DWELL2                      first dwell tick: door stays open
    // CLOSING = tick & DWELL & !DWELL2             second dwell tick: door closes
    // SERVICE = tick & !DWELL & REQ_HERE           a request here: open the door
    // MV_UP   = tick & !DWELL & !SERVICE & ANY_ABOVE & (DIR | !ANY_BELOW)
    // MV_DN   = tick & !DWELL & !SERVICE & ANY_BELOW & !MV_UP
    ld     TICK_EDGE
    and    C1_DWELL2
    sto    STAY
    ld     TICK_EDGE
    and    C1_DWELL
    andc   C1_DWELL2
    sto    CLOSING
    ld     TICK_EDGE
    andc   C1_DWELL
    and    REQ_HERE
    sto    SERVICE
    ld     C1_DIR
    orc    ANY_BELOW
    and    ANY_ABOVE
    and    TICK_EDGE
    andc   C1_DWELL
    andc   SERVICE
    sto    MV_UP
    ldc    MV_UP
    and    ANY_BELOW
    and    TICK_EDGE
    andc   C1_DWELL
    andc   SERVICE
    sto    MV_DN

    // ----------------------------------------------------------------------
    // car 1: door dwell (OEN gates the stores: only the chosen action writes)
    // ----------------------------------------------------------------------
    oen    STAY            // first dwell tick over
    ld     ZERO
    sto    C1_DWELL2
    oen    CLOSING         // second dwell tick: close the door
    ld     ZERO
    sto    C1_DWELL
    sto    DOOR1
    oen    ONE

    // ----------------------------------------------------------------------
    // car 1: service this floor - clear its requests, open the door
    // ----------------------------------------------------------------------
    ld     SERVICE
    and    POS1+0
    oen    RR              // at floor 0?
    ld     ZERO
    sto    CAB1+0
    sto    HALL_UP0
    ld     SERVICE
    and    POS1+1
    oen    RR              // at floor 1?
    ld     ZERO
    sto    CAB1+1
    sto    HALL_UP1
    sto    HALL_DN1
    ld     SERVICE
    and    POS1+2
    oen    RR              // at floor 2?
    ld     ZERO
    sto    CAB1+2
    sto    HALL_UP2
    sto    HALL_DN2
    ld     SERVICE
    and    POS1+3
    oen    RR              // at floor 3?
    ld     ZERO
    sto    CAB1+3
    sto    HALL_UP3
    sto    HALL_DN3
    ld     SERVICE
    and    POS1+4
    oen    RR              // at floor 4?
    ld     ZERO
    sto    CAB1+4
    sto    HALL_UP4
    sto    HALL_DN4
    ld     SERVICE
    and    POS1+5
    oen    RR              // at floor 5?
    ld     ZERO
    sto    CAB1+5
    sto    HALL_DN5
    oen    SERVICE
    ld     ONE
    sto    C1_DWELL
    sto    C1_DWELL2
    sto    DOOR1
    oen    ONE

    // ----------------------------------------------------------------------
    // car 1: move one floor (the position is one-hot; shift it)
    // ----------------------------------------------------------------------
    oen    MV_UP
    ld     POS1+4
    sto    POS1+5
    ld     POS1+3
    sto    POS1+4
    ld     POS1+2
    sto    POS1+3
    ld     POS1+1
    sto    POS1+2
    ld     POS1+0
    sto    POS1+1
    ld     ZERO
    sto    POS1+0
    ld     ONE
    sto    C1_DIR          // remember: going up
    oen    MV_DN
    ld     POS1+1
    sto    POS1+0
    ld     POS1+2
    sto    POS1+1
    ld     POS1+3
    sto    POS1+2
    ld     POS1+4
    sto    POS1+3
    ld     POS1+5
    sto    POS1+4
    ld     ZERO
    sto    POS1+5
    sto    C1_DIR          // remember: going down
    oen    ONE

    // ----------------------------------------------------------------------
    // car 1: direction lamps show what the car did on this tick
    // ----------------------------------------------------------------------
    oen    TICK_EDGE
    ld     MV_UP
    sto    UP1
    ld     MV_DN
    sto    DOWN1
    oen    ONE

    // ----------------------------------------------------------------------
    // car 2: start at floor 0 when no position bit is set yet (after reset)
    // ----------------------------------------------------------------------
    ld     POS2+0
    or     POS2+1
    or     POS2+2
    or     POS2+3
    or     POS2+4
    or     POS2+5
    ldc    RR              // RR = position unknown
    or     POS2+0
    sto    POS2+0

    // ----------------------------------------------------------------------
    // car 2: requests that concern this car, per floor
    // ----------------------------------------------------------------------
    // R_f = cabin button f | hall calls at f (unless car 1 is there: it takes them)
    ld     HALL_UP0
    andc   POS1+0
    or     CAB2+0
    sto    R0
    ld     HALL_UP1
    or     HALL_DN1
    andc   POS1+1
    or     CAB2+1
    sto    R1
    ld     HALL_UP2
    or     HALL_DN2
    andc   POS1+2
    or     CAB2+2
    sto    R2
    ld     HALL_UP3
    or     HALL_DN3
    andc   POS1+3
    or     CAB2+3
    sto    R3
    ld     HALL_UP4
    or     HALL_DN4
    andc   POS1+4
    or     CAB2+4
    sto    R4
    ld     HALL_DN5
    andc   POS1+5
    or     CAB2+5
    sto    R5

    // ----------------------------------------------------------------------
    // car 2: is there a request above / below the current floor?
    // ----------------------------------------------------------------------
    ld     R5
    and    POS2+4
    sto    ANY_ABOVE
    ld     R4
    or     R5
    and    POS2+3
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R3
    or     R4
    or     R5
    and    POS2+2
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R2
    or     R3
    or     R4
    or     R5
    and    POS2+1
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R1
    or     R2
    or     R3
    or     R4
    or     R5
    and    POS2+0
    or     ANY_ABOVE
    sto    ANY_ABOVE
    ld     R0
    and    POS2+1
    sto    ANY_BELOW
    ld     R0
    or     R1
    and    POS2+2
    or     ANY_BELOW
    sto    ANY_BELOW
    ld     R0
    or     R1
    or     R2
    and    POS2+3
    or     ANY_BELOW
    sto    ANY_BELOW
    ld     R0
    or     R1
    or     R2
    or     R3
    and    POS2+4
    or     ANY_BELOW
    sto    ANY_BELOW
    ld     R0
    or     R1
    or     R2
    or     R3
    or     R4
    and    POS2+5
    or     ANY_BELOW
    sto    ANY_BELOW

    // ----------------------------------------------------------------------
    // car 2: is there a request at the current floor?
    // ----------------------------------------------------------------------
    ld     R0
    and    POS2+0
    sto    REQ_HERE
    ld     R1
    and    POS2+1
    or     REQ_HERE
    sto    REQ_HERE
    ld     R2
    and    POS2+2
    or     REQ_HERE
    sto    REQ_HERE
    ld     R3
    and    POS2+3
    or     REQ_HERE
    sto    REQ_HERE
    ld     R4
    and    POS2+4
    or     REQ_HERE
    sto    REQ_HERE
    ld     R5
    and    POS2+5
    or     REQ_HERE
    sto    REQ_HERE

    // ----------------------------------------------------------------------
    // car 2: what this tick does (everything is gated by TICK_EDGE)
    // ----------------------------------------------------------------------
    // STAY    = tick & DWELL2                      first dwell tick: door stays open
    // CLOSING = tick & DWELL & !DWELL2             second dwell tick: door closes
    // SERVICE = tick & !DWELL & REQ_HERE           a request here: open the door
    // MV_UP   = tick & !DWELL & !SERVICE & ANY_ABOVE & (DIR | !ANY_BELOW)
    // MV_DN   = tick & !DWELL & !SERVICE & ANY_BELOW & !MV_UP
    ld     TICK_EDGE
    and    C2_DWELL2
    sto    STAY
    ld     TICK_EDGE
    and    C2_DWELL
    andc   C2_DWELL2
    sto    CLOSING
    ld     TICK_EDGE
    andc   C2_DWELL
    and    REQ_HERE
    sto    SERVICE
    ld     C2_DIR
    orc    ANY_BELOW
    and    ANY_ABOVE
    and    TICK_EDGE
    andc   C2_DWELL
    andc   SERVICE
    sto    MV_UP
    ldc    MV_UP
    and    ANY_BELOW
    and    TICK_EDGE
    andc   C2_DWELL
    andc   SERVICE
    sto    MV_DN

    // ----------------------------------------------------------------------
    // car 2: door dwell (OEN gates the stores: only the chosen action writes)
    // ----------------------------------------------------------------------
    oen    STAY            // first dwell tick over
    ld     ZERO
    sto    C2_DWELL2
    oen    CLOSING         // second dwell tick: close the door
    ld     ZERO
    sto    C2_DWELL
    sto    DOOR2
    oen    ONE

    // ----------------------------------------------------------------------
    // car 2: service this floor - clear its requests, open the door
    // ----------------------------------------------------------------------
    ld     SERVICE
    and    POS2+0
    oen    RR              // at floor 0?
    ld     ZERO
    sto    CAB2+0
    sto    HALL_UP0
    ld     SERVICE
    and    POS2+1
    oen    RR              // at floor 1?
    ld     ZERO
    sto    CAB2+1
    sto    HALL_UP1
    sto    HALL_DN1
    ld     SERVICE
    and    POS2+2
    oen    RR              // at floor 2?
    ld     ZERO
    sto    CAB2+2
    sto    HALL_UP2
    sto    HALL_DN2
    ld     SERVICE
    and    POS2+3
    oen    RR              // at floor 3?
    ld     ZERO
    sto    CAB2+3
    sto    HALL_UP3
    sto    HALL_DN3
    ld     SERVICE
    and    POS2+4
    oen    RR              // at floor 4?
    ld     ZERO
    sto    CAB2+4
    sto    HALL_UP4
    sto    HALL_DN4
    ld     SERVICE
    and    POS2+5
    oen    RR              // at floor 5?
    ld     ZERO
    sto    CAB2+5
    sto    HALL_DN5
    oen    SERVICE
    ld     ONE
    sto    C2_DWELL
    sto    C2_DWELL2
    sto    DOOR2
    oen    ONE

    // ----------------------------------------------------------------------
    // car 2: move one floor (the position is one-hot; shift it)
    // ----------------------------------------------------------------------
    oen    MV_UP
    ld     POS2+4
    sto    POS2+5
    ld     POS2+3
    sto    POS2+4
    ld     POS2+2
    sto    POS2+3
    ld     POS2+1
    sto    POS2+2
    ld     POS2+0
    sto    POS2+1
    ld     ZERO
    sto    POS2+0
    ld     ONE
    sto    C2_DIR          // remember: going up
    oen    MV_DN
    ld     POS2+1
    sto    POS2+0
    ld     POS2+2
    sto    POS2+1
    ld     POS2+3
    sto    POS2+2
    ld     POS2+4
    sto    POS2+3
    ld     POS2+5
    sto    POS2+4
    ld     ZERO
    sto    POS2+5
    sto    C2_DIR          // remember: going down
    oen    ONE

    // ----------------------------------------------------------------------
    // car 2: direction lamps show what the car did on this tick
    // ----------------------------------------------------------------------
    oen    TICK_EDGE
    ld     MV_UP
    sto    UP2
    ld     MV_DN
    sto    DOWN2
    oen    ONE

    // ----------------------------------------------------------------------
    // next scan
    // ----------------------------------------------------------------------
    nopf                   // back to address 0

// vim: sw=4 ts=4 et
