#!/usr/bin/env python3
'''
Regenerate assets.js: the board-side Python and the demo firmware images,
embedded so index.html is self-contained (works from file:// and from any
static host such as GitHub Pages).

Run after editing anything in board/ or firmware/:   python3 build_assets.py

uartPass.py is embedded verbatim (it is installed on the board's filesystem
and should stay readable there).  lisa_flash.py and ttlc_sim.py are only ever
sent to the board's RAM, so they are stripped of comments, docstrings and blank
lines first: the RP2040 has little free heap once the TT SDK is loaded.
'''
import ast
import base64
import hashlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
BOARD = os.path.join(HERE, '..', 'board')
FIRMWARE = os.path.join(HERE, '..', 'firmware')


def strip_python(src):
    tree = ast.parse(src)
    for node in ast.walk(tree):
        body = getattr(node, 'body', None)
        if (isinstance(body, list) and body and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)):
            del body[0]
            if not body:
                body.append(ast.Pass())
    return ast.unparse(tree) + '\n'


def read(path):
    with open(path) as f:
        return f.read()


def files(d, suffix=''):
    return {name: read(os.path.join(d, name)) for name in sorted(os.listdir(d))
            if not name.startswith('.') and name.endswith(suffix) and os.path.isfile(os.path.join(d, name))}


def rp2040_firmware():
    '''The MicroPython build with the SPI RAM emulation (firmware/rp2040/*.uf2),
    base64 so the app can write it to the RPI-RP2 drive; the README's first
    paragraph says where it came from.'''
    d = os.path.join(FIRMWARE, 'rp2040')
    name = next(n for n in sorted(os.listdir(d)) if n.endswith('.uf2'))
    with open(os.path.join(d, name), 'rb') as f:
        data = f.read()
    note = read(os.path.join(d, 'README.md')).split('\n\n')[1].replace('\n', ' ')
    return {'name': name, 'size': len(data), 'md5': hashlib.md5(data).hexdigest(),
            'note': note, 'uf2': base64.b64encode(data).decode()}


assets = {
    'uartPass.py': read(os.path.join(BOARD, 'uartPass.py')),
    'lisa_flash.py': strip_python(read(os.path.join(BOARD, 'lisa_flash.py'))),
    'ttlc_sim.py': strip_python(read(os.path.join(BOARD, 'ttlc_sim.py'))),
    'firmware': files(FIRMWARE),                            # LISA images
    'ttlc_firmware': files(os.path.join(FIRMWARE, 'ttlc'), '.hex'),   # TTLC (MC14500B) images
    'ttlc_sources': {**files(os.path.join(FIRMWARE, 'ttlc'), '.asm'),   # ...and their assembly + headers
                     **files(os.path.join(FIRMWARE, 'ttlc'), '.h')},
    'rp2040': rp2040_firmware(),                            # the RP2040's MicroPython with the SPI RAM emulation
}

out = os.path.join(HERE, 'assets.js')
with open(out, 'w') as f:
    f.write('// generated by build_assets.py - do not edit; edit board/ or firmware/ and rerun\n')
    f.write('window.LISA_ASSETS = ' + json.dumps(assets, indent=1) + ';\n')

print('wrote %s (%d bytes; lisa_flash.py %d, ttlc_sim.py %d bytes stripped)'
      % (out, os.path.getsize(out), len(assets['lisa_flash.py']), len(assets['ttlc_sim.py'])))
