
# DO NOT EDIT THIS FILE before reading the comments below:

# This is the default configuration for Tiny Tapeout projects. It should fit most designs.
# If you change it, please make sure you understand what you are doing. We are not responsible
# if your project fails because of a bad configuration.

# !!! DO NOT EDIT THIS FILE unless you know what you are doing !!!

# If you get stuck with this config, please open an issue or get in touch via the discord.

# Here are some of the variables you may want to change:

# PL_TARGET_DENSITY - You can increase this if Global Placement fails with error GPL-0302.
# Users have reported that values up to 0.8 worked well for them.
set ::env(PL_TARGET_DENSITY) 0.82

